package View;


import Process.Insert;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author xuanxuanvu
 */
public class Form extends javax.swing.JFrame {

    private Insert Form_SV;
    private DefaultTableModel tbModel;
    private String[] header;
    
    /**
     * Creates new form Form
     */
    
    public static String sql = "SELECT * FROM dbo.Student";
    public static Connection conn;
   
    public Form() {
        initComponents();
    }
    
    
    @Override
    protected Object clone() throws CloneNotSupportedException {
        return new CloneNotSupportedException();
    }
     
    protected Object readResolve() {
        return createIns();
    }
 
    private static class LazyInit{
        private static final Form Instance = new Form();
    }
     
    public static Form createIns() {
        return LazyInit.Instance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        txtfID = new javax.swing.JTextField();
        txtfName = new javax.swing.JTextField();
        txtfDate = new javax.swing.JTextField();
        txtfMath = new javax.swing.JTextField();
        txtfPhy = new javax.swing.JTextField();
        txtfChe = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbList = new javax.swing.JTable();
        btnOpen = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Thông tin sinh viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setText("Mã số sinh viên:");

        jLabel2.setText("Tên sinh viên:");

        jLabel3.setText("Ngày sinh:");

        jLabel4.setText("Điểm Toán:");

        jLabel5.setText("Điểm Lý:");

        jLabel6.setText("Điểm Hóa:");

        btnAdd.setText("Thêm");
        btnAdd.setEnabled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Sửa");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDel.setText("Xóa");
        btnDel.setEnabled(false);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfID)
                    .addComponent(txtfName)
                    .addComponent(txtfDate, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfMath)
                    .addComponent(txtfPhy)
                    .addComponent(txtfChe, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtfID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfMath, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtfPhy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfDate, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfChe))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "Danh sách sinh viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        tbList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MSSV", "Tên sinh viên", "Ngày sinh", "Toán", "Lý", "Hóa", "ĐTB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbList);
        if (tbList.getColumnModel().getColumnCount() > 0) {
            tbList.getColumnModel().getColumn(0).setResizable(false);
            tbList.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        btnOpen.setText("Mở CSDL");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        btnSearch.setText("Tìm kiếm");
        btnSearch.setEnabled(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnQuit.setText("Thoát");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOpen, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (!txtfID.getText().equals("") && !txtfName.getText().equals("") && !txtfDate.getText().equals("") && !txtfMath.getText().equals("") && !txtfPhy.getText().equals("") && !txtfChe.getText().equals("")){
            try{
                Form_SV.addSV(txtfID.getText(), txtfName.getText(), txtfDate.getText(), Float.parseFloat(txtfMath.getText()), Float.parseFloat(txtfPhy.getText()), Float.parseFloat(txtfChe.getText()));
                this.RefreshJTb();
                JOptionPane.showMessageDialog(null, "Thêm Sinh viên "+ txtfID.getText() +" Thành Công !", "Message", JOptionPane.INFORMATION_MESSAGE);
                txtfID.setText("");
                txtfName.setText("");
                txtfDate.setText("");
                txtfMath.setText("");
                txtfPhy.setText("");
                txtfChe.setText("");
            }catch (Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Message", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Vui lòng không được bỏ trống các ô thông tin!!!", "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        if (!txtfID.getText().equals("") && !txtfName.getText().equals("") && !txtfDate.getText().equals("") && !txtfMath.getText().equals("") && !txtfPhy.getText().equals("") && !txtfChe.getText().equals("")){
            try{
                int dialog = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa " + txtfName.getText() + " không?" , "Message", JOptionPane.YES_NO_OPTION);
                if (dialog == JOptionPane.YES_OPTION){
                    Form_SV.delSV(txtfID.getText());
                    this.RefreshJTb();
                    txtfID.setText("");
                    txtfName.setText("");
                    txtfDate.setText("");
                    txtfMath.setText("");
                    txtfPhy.setText("");
                    txtfChe.setText("");
                }
            }catch (Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Message", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Vui lòng không được bỏ trống các ô thông tin!!!", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        try{
            String Dbname = JOptionPane.showInputDialog(null, "Database name: ","Message",JOptionPane.INFORMATION_MESSAGE);
            String Username = JOptionPane.showInputDialog(null, "Username: ","Message",JOptionPane.INFORMATION_MESSAGE);
            String Password = JOptionPane.showInputDialog(null, "Password: ","Message",JOptionPane.INFORMATION_MESSAGE);
            Form_SV = new Insert(Dbname,Username,Password);
            if (Form_SV.isConnected())
            {
                CreateJTb();
                btnSearch.setEnabled(true);
                btnAdd.setEnabled(true);
                btnEdit.setEnabled(true);
                btnDel.setEnabled(true);
            }
            JOptionPane.showMessageDialog(null,"Mở CSDL thành công!","Message",1);    
        }catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        SearchSV.createIns().setVisible(true);
        RefreshJTb();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (!txtfID.getText().equals("") && !txtfName.getText().equals("") && !txtfDate.getText().equals("") && !txtfMath.getText().equals("") && !txtfPhy.getText().equals("") && !txtfChe.getText().equals("")){
            try{
                Form_SV.editSV(txtfID.getText(), txtfName.getText(), txtfDate.getText(), Float.parseFloat(txtfMath.getText()), Float.parseFloat(txtfPhy.getText()), Float.parseFloat(txtfChe.getText()));
                this.RefreshJTb();
                JOptionPane.showMessageDialog(null, "Sửa sinh viên "+ txtfName.getText() +" thành công!!!", "Message", JOptionPane.INFORMATION_MESSAGE);
                txtfID.setText("");
                txtfName.setText("");
                txtfDate.setText("");
                txtfMath.setText("");
                txtfPhy.setText("");
                txtfChe.setText("");
            }catch (Exception ex){
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Message", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Vui lòng không được bỏ trống các ô thông tin!!!", "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void tbListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListMouseClicked
        // TODO add your handling code here:
        if (tbList.getSelectedRowCount() == 1){
            int IndexRow_Temp = tbList.getSelectedRow();
            txtfID.setText(tbList.getValueAt(IndexRow_Temp,0).toString());
            txtfName.setText(tbList.getValueAt(IndexRow_Temp,1).toString());
            txtfDate.setText(tbList.getValueAt(IndexRow_Temp,2).toString());
            txtfMath.setText(tbList.getValueAt(IndexRow_Temp,3).toString());
            txtfPhy.setText(tbList.getValueAt(IndexRow_Temp,4).toString());
            txtfChe.setText(tbList.getValueAt(IndexRow_Temp,5).toString());
        }
    }//GEN-LAST:event_tbListMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btnAdd.setEnabled(false);
        btnEdit.setEnabled(false);
        btnDel.setEnabled(false);
        btnSearch.setEnabled(false);
        CreateJTb();
    }//GEN-LAST:event_formWindowOpened

    public void CreateJTb(){
        try {
            tbModel = new DefaultTableModel(0, 0);
            header = new String[] { "MSSV", "Tên sinh viên", "Ngày sinh", "Điểm Toán", "Điểm Lý", "Điểm Hóa", "ĐTB"};
            tbModel.setColumnIdentifiers(header);
            tbList.setModel(tbModel);
            if (Form_SV.isConnected()){
                ArrayList<STUDENT> arrList = Form_SV.getAll();
                for (int i = 0 ; i < arrList.size() ; i++){
                    Vector v_tmp = new Vector();
                    v_tmp.addElement(arrList.get(i).getID());
                    v_tmp.addElement(arrList.get(i).getName());
                    v_tmp.addElement(arrList.get(i).getDate());
                    v_tmp.addElement(arrList.get(i).getMath());
                    v_tmp.addElement(arrList.get(i).getPhy());
                    v_tmp.addElement(arrList.get(i).getChe());

                    DecimalFormat df = new DecimalFormat("#.##");
                    v_tmp.addElement(df.format(arrList.get(i).getAver()));

                    tbModel.addRow(v_tmp);
                }
            }
        }catch (ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);}
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void ClearJTb(){
        for (int i = (tbModel.getRowCount() - 1) ; i >= 0 ; i--){
            tbModel.removeRow(i);
        }
    }
    
    public void RefreshJTb()
    {
        try {
            ClearJTb();
            if (Form_SV.isConnected())
            {
                ArrayList<STUDENT> arrList = Form_SV.getAll();
                for (int i = 0 ; i < arrList.size() ; i++){
                    Vector v_tmp = new Vector();
                    v_tmp.addElement(arrList.get(i).getID());
                    v_tmp.addElement(arrList.get(i).getName());
                    v_tmp.addElement(arrList.get(i).getDate());
                    v_tmp.addElement(arrList.get(i).getMath());
                    v_tmp.addElement(arrList.get(i).getPhy());
                    v_tmp.addElement(arrList.get(i).getChe());

                    DecimalFormat df = new DecimalFormat("#.##");
                    v_tmp.addElement(df.format(arrList.get(i).getAver()));

                    tbModel.addRow(v_tmp);
                }
            }
        } 
        catch (ClassNotFoundException ex) 
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void RefreshJTb(int status){
            switch (status){
                case 1 :
                    ClearJTb();
                    STUDENT SV = Form_SV.searchID(SearchSV.createIns().getID());
                    Vector v_tmp = new Vector();
                    v_tmp.addElement(SV.getID());
                    v_tmp.addElement(SV.getName());
                    v_tmp.addElement(SV.getDate());
                    v_tmp.addElement(SV.getMath());
                    v_tmp.addElement(SV.getPhy());
                    v_tmp.addElement(SV.getChe());

                    DecimalFormat df = new DecimalFormat("#.##");
                    v_tmp.addElement(df.format(SV.getAver()));
                    tbModel.addRow(v_tmp);
                    break;
                case 2 :
                    ClearJTb();
                    SV = Form_SV.Search(SearchSV.createIns().getID(),SearchSV.createIns().getName());
                    v_tmp = new Vector();
                    v_tmp.addElement(SV.getID());
                    v_tmp.addElement(SV.getName());
                    v_tmp.addElement(SV.getDate());
                    v_tmp.addElement(SV.getMath());
                    v_tmp.addElement(SV.getPhy());
                    v_tmp.addElement(SV.getChe());
                    v_tmp.addElement(SV.getID());
                    v_tmp.addElement(SV.getName());
                    v_tmp.addElement(SV.getDate());
                    v_tmp.addElement(SV.getMath());
                    v_tmp.addElement(SV.getPhy());
                    v_tmp.addElement(SV.getChe());

                    df = new DecimalFormat("#.##");
                    v_tmp.addElement(df.format(SV.getAver()));
                    tbModel.addRow(v_tmp);
                    break;
                case 3 :
                    ClearJTb();
                    ArrayList<STUDENT> arrList = Form_SV.searchName(SearchSV.createIns().getName());
                    for (int i = 0 ; i < arrList.size() ; i++){
                        v_tmp = new Vector();
                        v_tmp.addElement(arrList.get(i).getID());
                        v_tmp.addElement(arrList.get(i).getName());
                        v_tmp.addElement(arrList.get(i).getDate());
                        v_tmp.addElement(arrList.get(i).getMath());
                        v_tmp.addElement(arrList.get(i).getPhy());
                        v_tmp.addElement(arrList.get(i).getChe());

                        df = new DecimalFormat("#.##");
                        v_tmp.addElement(df.format(arrList.get(i).getAver()));
                        tbModel.addRow(v_tmp);
                    }
                    break;
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form.createIns().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbList;
    private javax.swing.JTextField txtfChe;
    private javax.swing.JTextField txtfDate;
    private javax.swing.JTextField txtfID;
    private javax.swing.JTextField txtfMath;
    private javax.swing.JTextField txtfName;
    private javax.swing.JTextField txtfPhy;
    // End of variables declaration//GEN-END:variables
}
